### ISSUE TITLE
Tracker: v2.0 preliminary ideas

### ISSUE THREAD

**Issue by ibgreen** [uber-web/loaders.gl#118]
### MISSING FUNCTIONALITY
- [x] `parseFile` - Binary/Text parsing selection logic is fragile/likely incorrect in a few cases.
    - [ ] select based on input (string vs ArrayBuffer)
- [x] `loader.test...` - no way to test binary files. Most appropriate in many cases.
- [x] `decodeURI` - Uses `Buffers` instead of `ArrayBuffers` (loaders.gl is trying to standardize on the latter). Apart from the code base dissonance, this might make bundler include some `Buffer` polyfill?
