### ISSUE TITLE
Tracker: ArrowJS docs punch list

### ISSUE THREAD

**Issue by ibgreen** [uber-web/loaders.gl#209]
## Get started

- Examples
    - [ ] dated API, refresh, delete?

## Developer Guide.

- Big ints
    - [ ] better explanation needed
    - [ ] are they just 64 bit ints, or even bigger, variable length ints? Some more examples...

- data frame operations
    - [ ] Q: Does `length` queries get updated when filters are set, or just affects iteration?

- data types
    - [ ] needs a bit more text, add more examples

- data sources and sinks
    - [ ] A bit more text/examples

- Memory management - a bit more text.
    - [] Q: Assume memory chunks often get reallocated/joined on ingestion from streams if batches span multiple arraybuffer chunks.

- Tables
   - [ ] Double check examples...

- Typescript
   - [ ] Anything you want to add? Any ingenious constructions worth pointing out?

API Reference

TBA

**Comment by ibgreen** [comment]
@trxcllnt - I will need your help with the checklist above. Will start walkthough of API Reference now.

**Comment by ibgreen** [comment]
Adding link to future roadmap tracker but closing task due to inactivity
