### ISSUE TITLE
Tracker: 3D tiles tiling tool

### ISSUE THREAD

**Issue by jianhuang01** [uber-web/loaders.gl#480]
Here we are going to create a tiling tool to support potree and cesium 3D tiles generation.
- [x] Investigate potreeConverter and py3dtiles
- [x] Port potreeConverter to loaders.gl (#479)
- [x] Add cesium 3D tile spec support (#478)
- [x] add georeference support(#510)
- [x] add draco compression support (#515)
- [ ] Add geo-reference support to potree spec(#511)
