### ISSUE TITLE
Tracker: v1.0 Punchlist

### ISSUE THREAD

**Issue by ibgreen** [uber-web/loaders.gl#58]
Also see #7 GLTF Punchlist

## v1.0

- [x] Finalize design decisions on loader object API
- [x] Finalize design decisions on mesh formats, add conformance tests.
- [x] Refine module structure, particularly `core` and `images`
    - [x] Collect concerns about using core
    - [x] Reduce size of core
    - [x] Define clearly what goes into core and images
- [x] Define mechanism to register loaders so that they are available during parse
    - [x] Allows apps to cherry pick what loaders to include, and other frameworks to leverage them.
- [x] Clean up core image API (@ibgreen)
- [x] Fix browser image handling in `core` and `images` (@ibgreen)

### v0.9
- [x] ocular-gatsby website (@jckr)
- [x] Update deck.gl examples to use loaders.gl (@gnavvy)

### v0.8+
- [x] Pass on docs
- [x] Adopt ocular-dev-tools

### v0.7
- [x] Initial streaming support
- [x] remove IO code in deck.gl/test-utils (@ibgreen)
- [x] Copy `luma.gl` IO libraries into loaders.gl and consolidate (@ibgreen)
- [x] Move `@deck.gl/test-utils` IO code into loaders.gl (@ibgreen)
- [x] Add conformance tests for mesh category

### v0.6
- [x] New module `@loaders.gl/images` - Reconstruct luma.gl's original Node-based image loaders as new submodule.  (@ibgreen)
- [x] Log handling
- [x] All loading through loadFile/parseFile instead of using loaderObject methods
- [x] Remove IO code in luma.gl (@ibgreen)
- [x] Basic Threaded loading support

### v0.5 
- [x] Fixes for luma.gl glTF loading
- [x] Fix LAS loader (and make it synchronous) #20

### v0.3.x Add point cloud loaders
- [x] One npm module per format
- [x] Test cases for LAS/PLY/PCD/OBJ
- [x] Fix OBJ mesh loader

# OSS tasks
- [x] Break out from luma.gl
- [x] Approved
- [x] npm license crawler for dependencies
- [x] Flip public switch
- [x] Publish docs on gh pages
